delete from batches;
delete from companies;
delete from endorsements;
delete from sponsorships;
delete from events;
delete from projects;
delete from project_batches ;
delete from sessions;
delete from session_batches ;
delete from technologies;
delete from students;
delete from users;
delete from settings;